package cz.oluwagbemiga.speech_metric.controller;

import cz.oluwagbemiga.speech_metric.dto.RecognitionResponse;
import cz.oluwagbemiga.speech_metric.dto.RecognitionSuiteDTO;
import cz.oluwagbemiga.speech_metric.engine.RecognitionRequest;
import cz.oluwagbemiga.speech_metric.engine.SpeechEngine;
import cz.oluwagbemiga.speech_metric.entity.AudioFile;
import cz.oluwagbemiga.speech_metric.entity.RecognitionResult;
import cz.oluwagbemiga.speech_metric.service.AudioFileService;
import cz.oluwagbemiga.speech_metric.service.EngineService;
import cz.oluwagbemiga.speech_metric.service.RecognitionService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/recognition")
@Tag(name = "Recognition API", description = "Run speech recognition on stored audio files")
public class RecognitionController {

    private final AudioFileService audioFileService;
    private final RecognitionService recognitionService;
    private final EngineService engineService;

    public RecognitionController(
            AudioFileService audioFileService,
            RecognitionService recognitionService,
            EngineService engineService) {
        this.audioFileService = audioFileService;
        this.recognitionService = recognitionService;
        this.engineService = engineService;
    }


    @PostMapping("/{audioFileId}")
    @Operation(summary = "Recognize speech in an audio file",
            description = "Provide audioFile UUID and expected text. Optional query param model=small|large|whisper selects engine.")
    @Transactional
    public ResponseEntity<RecognitionResponse> recognize(
            @PathVariable UUID audioFileId,
            @RequestParam String expected,
            @RequestParam(name = "model", defaultValue = "whisper-small-q8") String modelSelect) {

        AudioFile audioFile = audioFileService.getById(audioFileId);

        // choose engine by model parameter
        SpeechEngine engine = engineService.getEngineByName(modelSelect);

        // run recognition and attach result to the audio file (engine adds to collection)
        engine.processAudio(new RecognitionRequest(audioFile, expected));

        // persist audio file with cascaded recognition result
        AudioFile saved = audioFileService.save(audioFile);
        RecognitionResult persisted = saved.getRecognitionResults().get(saved.getRecognitionResults().size() - 1);

        RecognitionResponse response = new RecognitionResponse(
                persisted.getId(),
                persisted.getModelName(),
                persisted.getRecognizedText(),
                persisted.getExpectedText(),
                persisted.getAccuracy(),
                persisted.getModelProcessingTimeMs()
        );
        return ResponseEntity.ok(response);
    }

    @PostMapping("/all-engines/{audioFileId}")
    @Operation(summary = "Recognize speech in an audio file",
            description = "Provide audioFile UUID and expected text. Optional query param model=small|large|whisper selects engine.")
    @Transactional
    public ResponseEntity<List<RecognitionResponse>> recognizeByAllEngines(
            @PathVariable UUID audioFileId,
            @RequestParam String expected) {

        List<RecognitionResponse> responses = recognitionService.recognizeAllEngines(audioFileId, expected);

        return ResponseEntity.ok(responses);
    }

    @PostMapping("/suite")
    @Operation(summary = "Run recognition suite",
            description = "Provide a JSON object mapping audio file UUIDs to expected transcripts. Runs all engines per audio file and returns aggregated results.")
    @Transactional
    public ResponseEntity<RecognitionSuiteDTO> runSuite(@RequestBody Map<UUID, String> expectedMap, @RequestParam UUID ownerId) {
        RecognitionSuiteDTO response = recognitionService.runSuite(expectedMap, ownerId);
        return ResponseEntity.ok(response);
    }

    @GetMapping("/engines")
    @Operation(summary = "List available engine names",
            description = "Returns the URL-friendly identifiers for every configured speech engine. Use one of these values in recognition requests.")
    public ResponseEntity<List<String>> getEngineNames() {
        List<String> names = engineService.getAllEngineNames();
        return ResponseEntity.ok(names);
    }

    @GetMapping("/results")
    @Operation(summary = "List recognition results by model",
            description = "Fetches every persisted recognition response generated by the specified speech model. Matching is case-insensitive.")
    public ResponseEntity<List<RecognitionResponse>> getResultsByModel(
            @Parameter(description = "Logical model name as persisted in recognition results", required = true)
            @RequestParam String modelName) {

        List<RecognitionResponse> responses = recognitionService.getResultsByModel(modelName);
        return ResponseEntity.ok(responses);
    }

}
